### ISSUE TITLE
Help with some emscripten stuff!

### ISSUE THREAD

**Issue by Moros1138** [L0huis/PGE-CMake#1]
I've recently started making a comprehensive CMake script template for the olcPixelGameEngine that will run on linux, macos, and windows using the various native toolchains. In my efforts I discovered a few things about the emscripten side of things.

I resolved the emscripten cache issues by using ``embuilder``. Here's a snippet from my cmake script that you could integrate into yours to streamline the process a bit, if you like!

```
    # PNG
    if (EMSCRIPTEN)
        execute_process(COMMAND embuilder build libpng OUTPUT_QUIET)
        execute_process(COMMAND embuilder build zlib OUTPUT_QUIET)
    endif (EMSCRIPTEN)
    
    find_package(PNG REQUIRED)
    target_link_libraries(${OutputExecutable} ${PNG_LIBRARIES})

    include_directories(${PNG_INCLUDE_DIRS})

```

note, the ``EMSCRIPTEN`` used as predicate above are the same as your ``PGE_USE_EMSCRIPTEN``.

This will allow cmake to process emscripten without needing to manually compile it first!

Thanks for posting this, it was helpful in guiding my approach. I hope you find this information useful!

**Comment by j-lohuis** [comment]
That is great to hear. I honestly didn't know `embuilder` was a thing to be honest :D.
Thank you for sharing your code snipped with me. I'll try to integrate it into my own script.

**Comment by Moros1138** [comment]
You're very welcome!
